version: 2
jobs:
	one:
		docker:
			- image: circleci/ruby:2.4.1
		steps:
			- checkout
			- run: echo "A first hello"
			- run: mkdir my_workspace
			- run: echo "Trying out workspace" > my_workspace/echo-output
			- persist_to_workspace:
				root: my_workspace
				path:
					- echo-output
	two:
		docker: 
			- image: circleci/ruby:2.4.1
			steps:
				- checkout
				- run: echo "A familiar hello"
				- attach-workspace:
					at: my_workspace
				- run: |
					if [[ $(cat my_workspace/echo-output) == "Trying out workspace" ]]; then
						echo "It worked!";
					else
						echo "Nope!"; exit 1
					fi
workflows:
	version: 2
	one_and_two:
		jobs:
			- one
			- two:
				- requires:
					- one
      
